import { DEFAULT_COURTS } from '../types/tournament';

export const INITIAL_EVENT_INFO = {
  name: '1º Open Arena DB de Futvôlei 2026',
  subtitle: 'Etapa Oficial de Eliminatória Dupla',
  location: 'Arena Praia & Sol — Quadras 1 a 4',
  city: 'São Paulo - SP',
  date: '2026-09-05',
  organizer: 'DB Sports Eventos',
  pixKey: 'arena.futvoleidb@gmail.com',
  pixKeyType: 'E-mail',
  pixReceiverName: 'DB Torneios & Eventos Esportivos',
  courts: DEFAULT_COURTS,
};

export const MOCK_TEAMS = [
  // Categoria C (Bronze) - 8 Duplas
  {
    id: 'team-c-1',
    categoryId: 'cat-c',
    player1: { name: 'Lucas "Canhota"', nickname: 'Canhotinha', phone: '11987654321', instagram: '@lucascanhota', shirtSize: 'M' },
    player2: { name: 'Gabriel Santos', nickname: 'Biel', phone: '11987654322', instagram: '@bielsantos', shirtSize: 'G' },
    displayName: 'Lucas & Gabriel',
    city: 'Santos - SP',
    isSeed: true,
    seedRank: 1,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 140,
    paymentDate: '2026-08-28',
    paymentNotes: 'Comprovante conferido via WhatsApp',
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'team-c-2',
    categoryId: 'cat-c',
    player1: { name: 'Felipe Alencar', nickname: 'Lipão', phone: '11987654323', instagram: '@felipelipao', shirtSize: 'G' },
    player2: { name: 'Matheus Ribeiro', nickname: 'Theus', phone: '11987654324', instagram: '@theus.fut', shirtSize: 'M' },
    displayName: 'Felipe & Matheus',
    city: 'Guarujá - SP',
    isSeed: true,
    seedRank: 2,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 140,
    paymentDate: '2026-08-29',
    paymentNotes: 'Pago no primeiro lote',
    createdAt: '2026-08-25T11:30:00Z',
  },
  {
    id: 'team-c-3',
    categoryId: 'cat-c',
    player1: { name: 'Rodrigo Pires', nickname: 'Digão', phone: '11987654325', instagram: '@digao.pires', shirtSize: 'GG' },
    player2: { name: 'Bruno Mendes', nickname: 'Brunão', phone: '11987654326', instagram: '@brunomendes_fut', shirtSize: 'G' },
    displayName: 'Rodrigo & Bruno',
    city: 'São Paulo - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_HALF',
    paymentMethod: 'PIX',
    paidAmount: 70,
    paymentDate: '2026-08-30',
    paymentNotes: 'Falta pagar 50% no dia do evento',
    createdAt: '2026-08-26T09:15:00Z',
  },
  {
    id: 'team-c-4',
    categoryId: 'cat-c',
    player1: { name: 'Gustavo Lima', nickname: 'Guga', phone: '11987654327', instagram: '@gugafutvolei', shirtSize: 'M' },
    player2: { name: 'Danilo Silva', nickname: 'Dan', phone: '11987654328', instagram: '@danilosilva', shirtSize: 'P' },
    displayName: 'Gustavo & Danilo',
    city: 'Campinas - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PENDING',
    paymentMethod: 'PIX',
    paidAmount: 0,
    paymentDate: null,
    paymentNotes: 'Aguardando comprovante',
    createdAt: '2026-08-27T14:20:00Z',
  },
  {
    id: 'team-c-5',
    categoryId: 'cat-c',
    player1: { name: 'Diego Torres', nickname: 'Dieguinho', phone: '11987654329', instagram: '@diegotorres.fut', shirtSize: 'M' },
    player2: { name: 'Rafael Costa', nickname: 'Rafa', phone: '11987654330', instagram: '@rafacosta_sp', shirtSize: 'G' },
    displayName: 'Diego & Rafael',
    city: 'São Bernardo - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'CASH',
    paidAmount: 140,
    paymentDate: '2026-08-30',
    paymentNotes: 'Pago em dinheiro na arena',
    createdAt: '2026-08-27T16:00:00Z',
  },
  {
    id: 'team-c-6',
    categoryId: 'cat-c',
    player1: { name: 'Thiago Martins', nickname: 'Thithi', phone: '11987654331', instagram: '@thiagomartins', shirtSize: 'M' },
    player2: { name: 'Leonardo Rocha', nickname: 'Léo', phone: '11987654332', instagram: '@leorochafut', shirtSize: 'P' },
    displayName: 'Thiago & Leonardo',
    city: 'São Paulo - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'EXEMPT',
    paymentMethod: 'TRANSFER',
    paidAmount: 0,
    paymentDate: '2026-08-25',
    paymentNotes: 'Cortesia patrocinador local',
    createdAt: '2026-08-28T10:45:00Z',
  },
  {
    id: 'team-c-7',
    categoryId: 'cat-c',
    player1: { name: 'Alexandre Peixoto', nickname: 'Xande', phone: '11987654333', instagram: '@xandepeixoto', shirtSize: 'G' },
    player2: { name: 'Marcos Vinícius', nickname: 'Marquinhos', phone: '11987654334', instagram: '@marquinhos_vinicius', shirtSize: 'M' },
    displayName: 'Alexandre & Marquinhos',
    city: 'Santo André - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 140,
    paymentDate: '2026-08-31',
    paymentNotes: 'PIX conferido',
    createdAt: '2026-08-29T11:00:00Z',
  },
  {
    id: 'team-c-8',
    categoryId: 'cat-c',
    player1: { name: 'Vitor Hugo', nickname: 'Vitinho', phone: '11987654335', instagram: '@vitinhofut', shirtSize: 'P' },
    player2: { name: 'Arthur Souza', nickname: 'Tutu', phone: '11987654336', instagram: '@arthursouza.fut', shirtSize: 'M' },
    displayName: 'Vitinho & Arthur',
    city: 'Mogi das Cruzes - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 140,
    paymentDate: '2026-08-31',
    paymentNotes: 'PIX automático',
    createdAt: '2026-08-30T08:30:00Z',
  },

  // Categoria B (Prata) - 6 Duplas
  {
    id: 'team-b-1',
    categoryId: 'cat-b',
    player1: { name: 'Eduardo Paiva', nickname: 'Edu', phone: '11987654340', instagram: '@edupaiva.fut', shirtSize: 'G' },
    player2: { name: 'Caio Magalhães', nickname: 'Caião', phone: '11987654341', instagram: '@caiomagalhaes', shirtSize: 'GG' },
    displayName: 'Edu & Caio',
    city: 'São Paulo - SP',
    isSeed: true,
    seedRank: 1,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 160,
    paymentDate: '2026-08-28',
    paymentNotes: '',
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'team-b-2',
    categoryId: 'cat-b',
    player1: { name: 'Renan Oliveira', nickname: 'Renanzinho', phone: '11987654342', instagram: '@renanzinho.fut', shirtSize: 'M' },
    player2: { name: 'Igor Ferreira', nickname: 'Iguinho', phone: '11987654343', instagram: '@igorferreira', shirtSize: 'M' },
    displayName: 'Renan & Igor',
    city: 'Santos - SP',
    isSeed: true,
    seedRank: 2,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 160,
    paymentDate: '2026-08-29',
    paymentNotes: '',
    createdAt: '2026-08-25T12:00:00Z',
  },
  {
    id: 'team-b-3',
    categoryId: 'cat-b',
    player1: { name: 'Marcelo Castro', nickname: 'Marcelinho', phone: '11987654344', instagram: '@marcelocastro', shirtSize: 'P' },
    player2: { name: 'Henrique Prado', nickname: 'Rique', phone: '11987654345', instagram: '@henriqueprado', shirtSize: 'M' },
    displayName: 'Marcelo & Henrique',
    city: 'Caraguatatuba - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PENDING',
    paymentMethod: 'PIX',
    paidAmount: 0,
    paymentDate: null,
    paymentNotes: 'Lembrar de cobrar na quinta',
    createdAt: '2026-08-27T15:00:00Z',
  },
  {
    id: 'team-b-4',
    categoryId: 'cat-b',
    player1: { name: 'Fábio Nogueira', nickname: 'Fabinho', phone: '11987654346', instagram: '@fabionogueira', shirtSize: 'G' },
    player2: { name: 'Lucas Prado', nickname: 'Luquinhas', phone: '11987654347', instagram: '@lucasprado_fut', shirtSize: 'M' },
    displayName: 'Fábio & Lucas',
    city: 'São Paulo - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'CARD',
    paidAmount: 160,
    paymentDate: '2026-08-30',
    paymentNotes: 'Cartão de crédito',
    createdAt: '2026-08-28T18:00:00Z',
  },
  {
    id: 'team-b-5',
    categoryId: 'cat-b',
    player1: { name: 'João Pedro', nickname: 'JP', phone: '11987654348', instagram: '@jp.futvolei', shirtSize: 'M' },
    player2: { name: 'Samuel Dantas', nickname: 'Samuca', phone: '11987654349', instagram: '@samucadantas', shirtSize: 'G' },
    displayName: 'JP & Samuca',
    city: 'Campinas - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 160,
    paymentDate: '2026-08-31',
    paymentNotes: '',
    createdAt: '2026-08-29T14:30:00Z',
  },
  {
    id: 'team-b-6',
    categoryId: 'cat-b',
    player1: { name: 'André Luiz', nickname: 'Dedé', phone: '11987654350', instagram: '@dede_futvolei', shirtSize: 'GG' },
    player2: { name: 'Bernardo Lima', nickname: 'Bê', phone: '11987654351', instagram: '@bernardolima', shirtSize: 'G' },
    displayName: 'André & Bernardo',
    city: 'Jundiaí - SP',
    isSeed: false,
    seedRank: null,
    paymentStatus: 'PAID_FULL',
    paymentMethod: 'PIX',
    paidAmount: 160,
    paymentDate: '2026-08-31',
    paymentNotes: '',
    createdAt: '2026-08-30T10:00:00Z',
  },
];
